// components/ui/footer.tsx
import { Box, Center, HStack, Text, VStack } from "@chakra-ui/layout"
import { Icon } from "@iconify/react"
import Link from "next/link"
import { ComponentProps } from "react"

type Props = {} & ComponentProps<"footer">
const AnswerdleFooter = ({ ...props }: Props) => {
    return (
        <footer {...props}>
            <VStack opacity={"50%"}>
                <HStack>
                    <a href={"https://github.com/p1atdev/answerdle"} target={"_blank"} rel={"noopener noreferrer"}>
                        <HStack>
                            <Icon icon="logos:github-icon" />
                            <Text>p1atdev/answerdle</Text>
                        </HStack>
                    </a>
                    <Box></Box>
                </HStack>
                <Center>
                    <Text>&copy; 2022 p1atdev</Text>
                </Center>
            </VStack>
        </footer>
    )
}

export default AnswerdleFooter

// src/components/Footer.vue
<template>
    <footer mb-8>
        <div flex flex-col text-gray-500 gap-y-1>
            <div grid grid-cols-1 place-items-center>
                <div flex items-center gap-x-4>
                    <a href="https://github.com/p1atdev/answerdle" target="_blank" rel="noreferrer noopener">
                        <div flex items-center gap-x-2>
                            <div class="i-akar-icons-github-fill text-lg"></div>
                            <p>GitHub</p>
                        </div>
                    </a>
                    <a href="https://twitter.com/p1atdev" target="_blank" rel="noreferrer noopener">
                        <div flex items-center gap-x-1>
                            <div class="i-akar-icons-twitter-fill text-lg"></div>
                            <p>@p1atdev</p>
                        </div>
                    </a>
                </div>
            </div>
            <div mx-auto>&copy; 2022 p1atdev</div>
        </div>
    </footer>
</template>
